### ISSUE TITLE
Attribute label should contain western name values (transliterate)

### ISSUE THREAD

**Issue by sfkeller** [geometalab/osmaxx-frontend#262] opened 2015-11-20 00:28 UTC
Currently, the `label` attribute is always populated with the transliterated `name`. Instead it should be

* `name` **if** it exists **and** it already is in a latin-based script, i.e. if `name` = transliterated `name`<br />**else**
* `name:en` **if** that exists<br />**else**
* `name:fr` **if** that exists<br />**else**
* `name:es` **if** that exists<br />**else**
* `name:de` **if** that exists<br />**else**
* transliterated `name` if `name` exists<br />**else**
* `NULL`

---
#### Original description
<del>Attribute `label` of all tables currently contains transliterated name value. But it should contain `name:en`, if not exists `name:de`, if not exists `name:fr`, if not exists transliterated (local) `name`.</del

**Comment by sfkeller** [comment] 2015-12-01 21:05
I think I can't help these days... Can anyone take over the assignment and resolution of this issue?

**Comment by hixi** [comment] 2016-01-12 10:18
This seems to be fixed, according to Stakeholder. 
But there seems to be a strange issue with symbols changed to arrows (maybe unicode issue?) -> streetlabels and similar (Arabian regions). Maybe also an issue with the osm import data?

**Comment by hixi** [comment] 2016-01-25 18:37
My comment will be fixed through geometalab/osmaxx-conversion-service#95

**Comment by das-g** [comment] 2016-02-04 08:31
@sfkeller: If `name` *already is* in a latin(-ish) script, i.e., if `name` and transliterated `name` are identical, should `label` have the value of `name` rather than of `name:(en|de|fr)`?

#### Example
For [ Node: Zurich (240025182)](http://www.openstreetmap.org/node/240025182), which has tags (amongst others) `name=Zürich` and `name:en=Zurich`, should `label` get value
- [ ] `Zürich` (with umlaut, from `name`)<br />or
- [ ] `Zurich` (without umlaut, from `name:en`)?

**Comment by das-g** [comment] 2016-02-04 14:16
> Attribute `label` of all tables currently contains transliterated name value. But it should contain `name:en`, if not exists `name:de`, if not exists `name:fr`, if not exists transliterated (local) `name`.

The precedence [we currently use](https://github.com/geometalab/osmaxx-conversion-service/blob/9ea552bb5e78538982ec9bcab61585d3ea1f703b/conversion_service/converters/gis_converter/bootstrap/sql/filter/geoname/020_geoname_p.sql#L17) is `en` > `fr` > `es` > `de`, (**not** `en` > `de` > `fr`). IIRC, the currently used precedence is the one that Geodienste requested in one of the initial meetings.

**Comment by hixi** [comment] 2016-02-10 14:27
This precedence been confirmed, so it should be `en > fr > es > de`.

**Comment by hixi** [comment] 2016-02-10 14:35
To be more specific on this issue, I'm trying to describe what I know, more or less a set of rules:

1. If the name and the transliterated name are the same, use 'name'
2. If they differ, use  `name:en` if not defined, use `name:fr` if not defined, use `name:es` if not defined, use `name:de`
3. If none of the above, use the transliterated value of `name`

and that value should be set on `label`.

**Comment by sfkeller** [comment] 2016-02-10 14:38
That sounds Ok for me, getting most out of the original data.

**Closed** 2016-03-02 08:05 UTC
Labels: ready, type:enhancement
