### ISSUE TITLE
Remove cemetery from POW

### ISSUE THREAD

**Issue by hixi** [geometalab/osmaxx-frontend#424] opened 2016-04-04 14:16 UTC

**Comment by geoSLG** [comment] 2016-04-12 15:38
`cemetery` and `grave_yard` should be called `burial_ground` and put into table `poi_p`

**Comment by das-g** [comment] 2016-04-12 15:42
duplicate of geometalab/osmaxx-conversion-service#124

**Closed by das-g** 2016-04-12 15:42 UTC
